USE EbDb;
CREATE TABLE Users(user_id INT IDENTITY PRIMARY KEY, name NVARCHAR(100), phone NVARCHAR(20), email NVARCHAR(150) UNIQUE, dob DATE, password NVARCHAR(256));
CREATE TABLE Admins(admin_id INT IDENTITY PRIMARY KEY, username NVARCHAR(50) UNIQUE, password NVARCHAR(256));
CREATE TABLE Connections(connection_id INT IDENTITY PRIMARY KEY, user_id INT NULL, consumer_number NVARCHAR(30) UNIQUE, name NVARCHAR(100), phone NVARCHAR(20), email NVARCHAR(150), address NVARCHAR(300), locality NVARCHAR(50), type NVARCHAR(50), load INT, connection_type NVARCHAR(50), id_proof_path NVARCHAR(200), photo_path NVARCHAR(200), status NVARCHAR(20) DEFAULT 'Pending', created_at DATETIME DEFAULT GETDATE());
CREATE TABLE ElectricityBill(bill_id INT IDENTITY PRIMARY KEY, consumer_number NVARCHAR(30), consumer_name NVARCHAR(100), units_consumed INT, bill_amount DECIMAL(10,2), bill_date DATETIME, status NVARCHAR(10) DEFAULT 'Unpaid');
CREATE TABLE Payments(payment_id INT IDENTITY PRIMARY KEY, user_id INT NULL, consumer_number NVARCHAR(30), bill_id INT NULL, amount DECIMAL(10,2), payment_date DATETIME DEFAULT GETDATE(), method NVARCHAR(20), txn_ref NVARCHAR(100), status NVARCHAR(20));
CREATE TABLE TariffSlabs(SlabId INT IDENTITY PRIMARY KEY, MinUnits INT, MaxUnits INT NULL, Rate DECIMAL(10,2));
CREATE TABLE Outages(OutageId INT IDENTITY PRIMARY KEY, Location NVARCHAR(200), Status NVARCHAR(100), StartTime DATETIME, EndTime DATETIME);
CREATE TABLE Concerns(concern_id INT IDENTITY PRIMARY KEY, user_id INT, subject NVARCHAR(200), message NVARCHAR(MAX), status NVARCHAR(20), created_at DATETIME DEFAULT GETDATE());
INSERT INTO Admins(username,password) VALUES('admin','admin123');
INSERT INTO TariffSlabs(MinUnits,MaxUnits,Rate) VALUES (0,100,0),(101,300,1.5),(301,600,3.5),(601,1000,5.5),(1001,NULL,7.5);
INSERT INTO Outages(Location,Status,StartTime,EndTime) VALUES ('Ranchi - Sector 2','Scheduled Maintenance','2025-09-01 10:00','2025-09-01 15:00');
